### ISSUE TITLE
Q-Factor in Accept Header isn't contemplated

### ISSUE THREAD

**Issue by thepabloaguilar** [CoCongV/sanic-restful#1]
I made a resource with a simple response, when a request is made with header:
`Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`, I receive an error, `NotAcceptable("Not Accetable")`.
In this header we have **q-factor weighting**([Accept Header Documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept)). The function `get_accept_mimetypes` & `best_match_accept_mimetype` in `util.py` file doesn't contemplate this.

My Resource:
```python3
from sanic_restful import Resource


class HealthStatusResource(Resource):
    async def get(self, request) -> dict:
        return {'status': 'OK'}
```

Partial solution:
```python3
from sanic_restful import Resource
from sanic.response import json


class HealthStatusResource(Resource):
    async def get(self, request):
        return json({'status': 'OK'})
```

If return is `BaseHTTPResponse` instance the method that generates this error isn't called.

**Comment by CoCongV** [comment]
Thanks for the report,
The issue has been solved in 0.0.8
